Este projecto tem como objetivo realizar uma previsão de avaliação que o utilizador irá atribuir à um determinado filme, baseado no histórico de avaliações prévio, em ratings.csv, da MovieLens.

1- Download dos Ficheiros

In [1]:
import pandas as pd

ratings = pd.read_csv("ratings.csv")
movies = pd.read_csv("movies.csv")

display(ratings.head())
display(movies.head())

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [2]:
print("Numero de avaliacoes:",len(ratings))
print("Numero de utilizadores:",ratings["userId"].nunique())
print("Numero de filmes no catalogo:",len(movies))

Numero de avaliacoes: 100836
Numero de utilizadores: 610
Numero de filmes no catalogo: 9742

In [3]:
print("Valores em falta nas avaliacoes:\n")
print(ratings.isna().sum())

Valores em falta nas avaliacoes:

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

2- Para maior facilidade visual, juntar-se-ão as avaliações aos títulos

In [4]:
avaliacoes = ratings.merge(
    movies, 
    on="movieId",
    how="left",
    validate="many_to_one"
)

display(avaliacoes[["userId","title","rating"]].head(10))

   userId                        title  rating
0       1             Toy Story (1995)     4.0
1       1      Grumpier Old Men (1995)     4.0
2       1                  Heat (1995)     4.0
3       1  Seven (a.k.a. Se7en) (1995)     5.0
4       1   Usual Suspects, The (1995)     5.0
5       1   From Dusk Till Dawn (1996)     3.0
6       1         Bottle Rocket (1996)     5.0
7       1            Braveheart (1995)     4.0
8       1               Rob Roy (1995)     5.0
9       1        Canadian Bacon (1995)     5.0

Aqui, rastreia-se o que o utilizador 1 (userId:1) tem avaliado